environment: development

auto: true
server: false
safe: false
permalink: /:title/
exclude: ["do.cmd", "**/*.haml", "**/*.coffee", "Gemfile", "Gemfile.lock"]
leave: ["css/", ".livereload", "**/*.ajax.html"]
ignore:
  - _sass/**/*
  - _solution/**/*
  - _fonts/**/*
  - _json/**/*

markdown: redcarpet
redcarpet:
  extensions: [autolink, tables, smart]

sitemap:
  url: http://www.jaapsuter.com

indextank_storage_dir: .
indextank_index: JaapSuter
indextank_api_url: http://:GJL2XlS6C3kv99@467q.api.indextank.com
indextank_excludes: [index.html, 404.html, ^/secret/]
